CHANGELOG.md
lib/service/businessLogic.coffee
lib/service/dataLink.coffee
lib/service/kinveyCompletionHandler.coffee
test/lib/businessLogic.test.coffee
test/lib/dataLink.test.coffee

- Modularize completionHandlers
- Add completionHandlers to BL task resolution
- Add BL task capabilities to backend-sdk
- Update unit tests
- Fix an error message typo in code and corresponding test

BACK-1304: Add BL task execution capabilities to backend-sdk

---

lib/service/logger.js
test/lib/logger.test.js

… and updated tests accordingly

BACK-1600: Fixed logger.js error where stdout buffer wasn't properly flushed

---

README.md

fix syntax errors with service construction

---

README.md
lib/service/moduleGenerator.js
lib/service/modules/userStore.js
test/lib/moduleGenerator.test.js
test/lib/modules/dataStore.test.js
test/lib/modules/userStore.test.js

Added `modules.userStore` for creating, updating, finding, deleting, suspending, and restoring user entities.

BACK-2035 Add userstore

---

README.md

useBl -> skipBl

---

lib/flex.js
lib/service/auth.js
lib/service/modules/dataStore.js
lib/service/modules/userStore.js
test/lib/auth.test.js
test/lib/data.test.js
test/lib/flex.test.js
test/lib/functions.test.js

Note that auth doesn't use the base completion handler and has a different error format, which conforms to the specification of OAuth2.

Back 2076 add auth support into flex

---

lib/service/modules/baseStore.js

@mjsalinger per our hangout discussion. No Mocha tests this time.

typo in error response callback

---

lib/flex.js
test/lib/flex.test.js

* Disable shared secret for ServiceDiscovery
* Do not return an error object to completionCallback, return a result with an error

BACK-2407 BACK-2401 Fix Shared Secrets

---

lib/service/auth.js
test/lib/auth.test.js

Added `notImplemented` as a complete handler for FlexAuth.

BACK-2395 Missing Flex Auth NotImplemented Handler

---

lib/flex.js
test/lib/flex.test.js
test/lib/modules/dataStore.test.js

Add the sdk version to the task object before validation for `authKey`. Add check for it in unit test. Small fix for unit test for count() missing a query.

FLEX-172 Append SDK version

---

lib/service/modules/kinveyEntity.js
test/lib/modules/entity.test.js

added reader and update to entity to support using roles and adding to collections.

add role helper functions to add properties to entity

---

.travis.yml
README.md

Changes:
- integrate with Travis for the execution of flex-sdk tests
- add build status to README file

QA-216: Integrate with Travis

---

.eslintignore
.eslintrc
package-lock.json
package.json

Changes:
- update lint devDependencies to their latest version;
- add .eslintignore file;
- modify .eslintrc file to extend Kinvey specified lint rules
- remove airbnb dependecy

QA-228: Adjust lint operations

---

package-lock.json
package.json

Update version of sinon to latest, which includes a patch for a vulnerability in the version we've been using (7.1.1).

Fix failing security tests

---

lib/service/data.js
test/unit/lib/data.test.js

@mjsalinger - please let me know if I have missed something.

BACK-3877: Add support for insertMany

---

lib/service/modules/dataStore.js
package-lock.json
package.json
test/unit/lib/modules/dataStore.test.js

Tests are not done yet. Starting this PR so you can verify the approach I have taken.

BACK-4117: For multi-insert, send requests in batches of 100 entities

---

CHANGELOG.md
lib/service/modules/dataStore.js
package-lock.json
package.json
test/unit/lib/modules/dataStore.test.js

KDEV-294: Add create function supporting multi-insert

---

CHANGELOG.md
lib/flex.js
package.json

Changes:
* Update logged message on error from complete callback

KDEV-720: Update message on error from complete callback

---

lib/flex.js
lib/service/moduleGenerator.js
package-lock.json
package.json
test/unit/lib/flex.test.js
test/unit/lib/modules/dataStore.test.js
test/unit/lib/modules/endpointRunner.test.js
test/unit/lib/modules/groupStore.test.js
test/unit/lib/modules/roleStore.test.js
test/unit/lib/modules/userStore.test.js

Changes:
* Change default api version
* Remove api version fallback from KCS task's response headers
* Update tests
* Change major package version

KDEV-842: Switch default KCS api version to 5

---

lib/service/modules/kinveyEntity.js
package-lock.json
package.json
test/unit/lib/auth.test.js
test/unit/lib/data.test.js
test/unit/lib/functions.test.js
test/unit/lib/moduleGenerator.test.js
test/unit/lib/modules/backendContext.test.js
test/unit/lib/modules/dataStore.test.js
test/unit/lib/modules/email.test.js
test/unit/lib/modules/endpointRunner.test.js
test/unit/lib/modules/entity.test.js
test/unit/lib/modules/groupStore.test.js
test/unit/lib/modules/kinveyDate.test.js
test/unit/lib/modules/push.test.js
test/unit/lib/modules/query.test.js
test/unit/lib/modules/requestContext.test.js
test/unit/lib/modules/roleStore.test.js
test/unit/lib/modules/tempObjectStore.test.js
test/unit/lib/modules/userStore.test.js

* removed unneeded return statements;
* change the way BSON is initialised

KDEV-1718: Bump bson to version 4.3.0

---

.eslintrc
CHANGELOG.md
lib/service/functions.js
package-lock.json
package.json
test/unit/lib/functions.test.js
test/unit/lib/modules/requestContext.test.js
test/unit/lib/modules/userStore.test.js

https://kinvey.atlassian.net/browse/KDEV-1626

KDEV 1626: Add login hooks properties

---

lib/service/data.js
lib/service/functions.js
lib/service/kinveyCompletionHandler.js
test/unit/lib/functions.test.js
test/unit/lib/modules/requestContext.test.js

https://progresssoftware.atlassian.net/browse/KDEV-2079

KDEV-2079: Persist custom req properties between pre post hooks
